spring.application.name=SpringJwtLogin

spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=E68n2N7LzS8vN4pH6tV9yB2lQ8wX5zL1qZ3sU7xA9cD4fG6hJ8kL2nP0rT1vW3Y
jwt.expiration=3600000

logging.level.org.springframework.security=INFO
